import { useEffect, useRef, useState } from 'react'; import BookRelationSelector from './BookRelationSelector'; import LessonEditor from './LessonEditor'; import ResourceUploader from './ResourceUploader';
import type { AdminBookOption, AdminCourseDraft, AdminLesson, AdminModule } from '../../types/admin'; import styles from './AdminBuilder.module.css';
const uid=()=>crypto.randomUUID(); const slugify=(v:string)=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const blankLesson=(n=1):AdminLesson=>({clientId:uid(),title:`Lección ${n}`,slug:`leccion-${uid().slice(0,8)}`,description:'',estimatedMinutes:15,status:'draft',bookIds:[],blocks:[]});
const blankModule=(n=1):AdminModule=>({clientId:uid(),title:`Módulo ${n}`,description:'',bookIds:[],lessons:[blankLesson()]});
const move=<T,>(items:T[],i:number,d:-1|1)=>{const t=i+d;if(t<0||t>=items.length)return items;const c=[...items];[c[i],c[t]]=[c[t],c[i]];return c};
type Props={initialCourse:AdminCourseDraft;books:AdminBookOption[]};
export default function CourseBuilder({initialCourse,books}:Props){const [course,setCourse]=useState(initialCourse);const [selected,setSelected]=useState<string|undefined>(initialCourse.modules[0]?.lessons[0]?.clientId);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const first=useRef(true);
 const updateModule=(clientId:string,next:AdminModule)=>setCourse(c=>({...c,modules:c.modules.map(m=>m.clientId===clientId?next:m)}));
 const save=async(published=course.published,automatic=false)=>{if(!course.title.trim()||!course.slug.trim()){if(!automatic)setMessage('Completa el título y el slug.');return}setBusy(true);const response=await fetch('/api/admin/courses/save',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...course,published})});const result=await response.json();setBusy(false);if(!response.ok){setMessage(result.error??'No se pudo guardar.');return}setMessage(automatic?'Cambios guardados automáticamente.':published?'Curso publicado.':'Borrador guardado.');if(!automatic)setCourse(c=>({...c,id:result.id,published}));if(!course.id&&!automatic)location.href=`/admin/cursos/${result.id}/editar`;};
 useEffect(()=>{if(first.current){first.current=false;return}if(!course.id)return;const timer=setTimeout(()=>void save(course.published,true),1800);return()=>clearTimeout(timer)},[course]);
 const selectedLesson=course.modules.flatMap(m=>m.lessons).find(l=>l.clientId===selected);
 return <div className={styles.builder}><section className={styles.panel}><div className={styles.toolbar}><div><h1>{course.id?'Editar curso':'Crear curso'}</h1><span className={styles.status}>{course.published?'Publicado':'Borrador'}</span></div><div className={styles.actions}><button className={styles.button} disabled={busy} onClick={()=>save(false)}>{busy?'Guardando…':'Guardar borrador'}</button><button className={`${styles.button} ${styles.primary}`} disabled={busy} onClick={()=>save(true)}>Publicar</button></div></div>{message&&<p className={message.includes('No ')||message.includes('Completa')?styles.error:styles.success}>{message}</p>}</section>
 <section className={styles.panel}><div className={styles.grid}><label className={styles.field}>Título*<input required value={course.title} onChange={e=>setCourse({...course,title:e.target.value,slug:course.slug||slugify(e.target.value)})}/></label><label className={styles.field}>Slug*<input required pattern="[a-z0-9-]+" value={course.slug} onChange={e=>setCourse({...course,slug:slugify(e.target.value)})}/></label><label className={`${styles.field} ${styles.wide}`}>Resumen*<textarea maxLength={300} value={course.shortDescription} onChange={e=>setCourse({...course,shortDescription:e.target.value})}/></label><label className={`${styles.field} ${styles.wide}`}>Descripción completa<textarea rows={5} value={course.description} onChange={e=>setCourse({...course,description:e.target.value})}/></label><label className={styles.field}>Categoría<input value={course.category} onChange={e=>setCourse({...course,category:e.target.value})}/></label><label className={styles.field}>Nivel<select value={course.level} onChange={e=>setCourse({...course,level:e.target.value as AdminCourseDraft['level']})}><option>Básico</option><option>Intermedio</option><option>Avanzado</option></select></label><label className={styles.field}>Duración (horas)<input type="number" min="0" step=".5" value={course.durationHours} onChange={e=>setCourse({...course,durationHours:Number(e.target.value)})}/></label><label className={styles.field}>Instructor<input value={course.instructorName} onChange={e=>setCourse({...course,instructorName:e.target.value})}/></label></div>
 {course.id?<ResourceUploader bucket="course-covers" courseId={course.id} onUploaded={r=>setCourse({...course,coverPath:r.path})}/>:<p className={styles.muted}>Guarda el borrador antes de cargar la portada y otros archivos.</p>}<BookRelationSelector books={books} selectedIds={course.bookIds} onChange={bookIds=>setCourse({...course,bookIds})}/></section>
 <section className={styles.panel}><div className={styles.toolbar}><div><h2>Estructura del curso</h2><p className={styles.muted}>Reordena, duplica y edita módulos y lecciones.</p></div><button className={styles.button} onClick={()=>setCourse({...course,modules:[...course.modules,blankModule(course.modules.length+1)]})}>+ Módulo</button></div><div className={styles.stack}>{course.modules.map((module,mi)=><article className={styles.item} key={module.clientId}><div className={styles.toolbar}><input className={styles.control} value={module.title} onChange={e=>updateModule(module.clientId,{...module,title:e.target.value})}/><div className={styles.actions}><button className={styles.button} onClick={()=>setCourse({...course,modules:move(course.modules,mi,-1)})}>↑</button><button className={styles.button} onClick={()=>setCourse({...course,modules:move(course.modules,mi,1)})}>↓</button><button className={styles.button} onClick={()=>setCourse({...course,modules:[...course.modules.slice(0,mi+1),{...module,clientId:uid(),title:`${module.title} (copia)`,lessons:module.lessons.map(l=>({...l,clientId:uid(),slug:`${l.slug}-copia-${uid().slice(0,4)}`,blocks:l.blocks.map(b=>({...b,clientId:uid()}))}))},...course.modules.slice(mi+1)]})}>Duplicar</button><button className={`${styles.button} ${styles.danger}`} onClick={()=>setCourse({...course,modules:course.modules.filter(m=>m.clientId!==module.clientId)})}>Eliminar</button></div></div><textarea className={styles.control} value={module.description} onChange={e=>updateModule(module.clientId,{...module,description:e.target.value})} placeholder="Descripción del módulo"/><BookRelationSelector books={books} selectedIds={module.bookIds} onChange={bookIds=>updateModule(module.clientId,{...module,bookIds})} label="Libros del módulo"/><div className={styles.actions}>{module.lessons.map((lesson,li)=><span key={lesson.clientId}><button className={`${styles.button} ${selected===lesson.clientId?styles.primary:''}`} onClick={()=>setSelected(lesson.clientId)}>{li+1}. {lesson.title}</button><button aria-label="Duplicar lección" className={styles.button} onClick={()=>updateModule(module.clientId,{...module,lessons:[...module.lessons.slice(0,li+1),{...lesson,clientId:uid(),title:`${lesson.title} (copia)`,slug:`${lesson.slug}-copia-${uid().slice(0,4)}`,blocks:lesson.blocks.map(b=>({...b,clientId:uid()}))},...module.lessons.slice(li+1)]})}>⧉</button><button aria-label="Subir lección" className={styles.button} onClick={()=>updateModule(module.clientId,{...module,lessons:move(module.lessons,li,-1)})}>↑</button><button aria-label="Bajar lección" className={styles.button} onClick={()=>updateModule(module.clientId,{...module,lessons:move(module.lessons,li,1)})}>↓</button></span>)}<button className={styles.button} onClick={()=>{const l=blankLesson(module.lessons.length+1);updateModule(module.clientId,{...module,lessons:[...module.lessons,l]});setSelected(l.clientId)}}>+ Lección</button></div></article>)}</div></section>
 {selectedLesson&&<LessonEditor lesson={selectedLesson} books={books} courseId={course.id} onChange={next=>setCourse({...course,modules:course.modules.map(m=>({...m,lessons:m.lessons.map(l=>l.clientId===next.clientId?next:l)}))})}/>}</div>}
