import { useState } from 'react'; import BlockEditor from './BlockEditor'; import BookRelationSelector from './BookRelationSelector';
import { ADMIN_BLOCK_TYPES, type AdminBlockType, type AdminBookOption, type AdminLesson } from '../../types/admin'; import styles from './AdminBuilder.module.css';
const uid=()=>crypto.randomUUID(); const move=<T,>(items:T[],index:number,direction:-1|1)=>{const target=index+direction;if(target<0||target>=items.length)return items;const copy=[...items];[copy[index],copy[target]]=[copy[target],copy[index]];return copy};
type Props={lesson:AdminLesson;books:AdminBookOption[];courseId?:string;onChange:(lesson:AdminLesson)=>void};
export default function LessonEditor({lesson,books,courseId,onChange}:Props){const [preview,setPreview]=useState(false);
 const add=(type:AdminBlockType)=>onChange({...lesson,blocks:[...lesson.blocks,{clientId:uid(),type,content:{title:'',body:''}}]});
 return <section className={`${styles.panel} ${styles.builder}`}><div className={styles.toolbar}><div><h2>Editor de lección</h2><span className={styles.muted}>{lesson.blocks.length} bloques</span></div><div className={styles.actions}><button className={styles.button} onClick={()=>setPreview(!preview)}>{preview?'Editar':'Vista previa'}</button></div></div>
 <div className={styles.grid}><label className={styles.field}>Título*<input required value={lesson.title} onChange={e=>onChange({...lesson,title:e.target.value})}/></label><label className={styles.field}>Slug*<input required value={lesson.slug} onChange={e=>onChange({...lesson,slug:e.target.value})}/></label><label className={styles.field}>Duración estimada (min)<input type="number" min="1" max="1440" value={lesson.estimatedMinutes} onChange={e=>onChange({...lesson,estimatedMinutes:Number(e.target.value)})}/></label><label className={styles.field}>Estado<select value={lesson.status} onChange={e=>onChange({...lesson,status:e.target.value as AdminLesson['status']})}><option value="draft">Borrador</option><option value="published">Publicada</option></select></label><label className={`${styles.field} ${styles.wide}`}>Descripción<textarea rows={3} value={lesson.description} onChange={e=>onChange({...lesson,description:e.target.value})}/></label></div>
 <BookRelationSelector books={books} selectedIds={lesson.bookIds} onChange={bookIds=>onChange({...lesson,bookIds})} label="Lecturas recomendadas"/>
 {preview?<div className={styles.preview}>{lesson.blocks.map(block=><section key={block.clientId}><h3>{String(block.content.title||block.type)}</h3><p style={{whiteSpace:'pre-wrap'}}>{String(block.content.body||block.content.url||'')}</p></section>)}</div>:<><div><h3>Agregar bloque</h3><div className={styles.blockTypes}>{ADMIN_BLOCK_TYPES.map(type=><button type="button" className={`${styles.button} ${styles.compact}`} onClick={()=>add(type)} key={type}>{type}</button>)}</div></div><div className={styles.stack}>{lesson.blocks.length?lesson.blocks.map((block,index)=><BlockEditor key={block.clientId} block={block} books={books} courseId={courseId} onChange={next=>onChange({...lesson,blocks:lesson.blocks.map(item=>item.clientId===block.clientId?next:item)})} onDuplicate={()=>onChange({...lesson,blocks:[...lesson.blocks.slice(0,index+1),{...block,clientId:uid(),content:{...block.content}},...lesson.blocks.slice(index+1)]})} onMove={direction=>onChange({...lesson,blocks:move(lesson.blocks,index,direction)})}/>):<p className={styles.muted}>Agrega el primer bloque para comenzar.</p>}</div></>}
 </section>}
